# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.8'
# Services
services:

  # PHP Interpreter
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    image: markmarilag27/php/8:minimal
    container_name: php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - default

  # Webserver
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  # Database
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql/
    networks:
      - default

  # Mail
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
        - "1025:1025"
        - "8025:8025"
    networks:
      - default

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - default

  # Minio
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "8900:8900"
    environment:
      MINIO_ROOT_USER: laravel
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data/minio
    networks:
      - default
    command: minio server /data/minio --console-address ":8900"

# Networks
networks:
  default:
    driver: bridge

# Volumes
volumes:
  mysql-data:
    driver: local
  minio-data:
    driver: local
  redis-data:
    driver: local
